### ISSUE TITLE
NewContextFromMsgPack should handle wired cmetrics msgpack format

### ISSUE THREAD

**Issue by cosmo0920** [calyptia/cmetrics-go#6]
Currently, cmetrics-go does not handle wired msgpack buffer format (Just assumed single cmetrics msgpack buffer):
https://github.com/calyptia/cmetrics-go/blob/9026febc792fd2a2c4c52d12f30fe74d8e4249b3/cmetrics.go#L137-L151

In Fluentd side, single cmetrics context buffer is too hard to implement.

I'm trying to support this wired type of cmetrics msgpack buffer decoding on:
https://github.com/calyptia/cmetrics-ruby/blob/6f5de78ad6994fc7e7382b41d4b22bcc4bf49078/ext/cmetrics/cmetrics_serde.c#L126-L151

Or, using msgpack buffer's offset for resuming the latter buffers decoding:
https://github.com/calyptia/cmetrics-ruby/blob/6f5de78ad6994fc7e7382b41d4b22bcc4bf49078/ext/cmetrics/cmetrics_serde.c#L114

**Comment by niedbalski** [comment]
Fixed by #7

**Comment by cosmo0920** [comment]
Thanks!
